name: Build everyday

on:
  push:
    branches:
      - 'login-limit'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-modified:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Build
        run: python3 build.py

      - name: check for changes
        run: echo "changes_exist=$(git diff --exit-code)" >> $GITHUB_ENV

      - name: Commit files
        if: env.changes_exist == 'true'
        run: |
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git commit -m 'Daily auto build' -a
      - name: Push changes
        if: env.changes_exist == 'true'
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}